### ISSUE TITLE
Delete applet raise error: RuntimeError: SW match failed! Expected 9000 and got 6a88.

### ISSUE THREAD

**Issue by liuwei-network** [mrlnc/HelloSTK2#2]
Hello,

Thanks for update this STK, I've install the helloSTK.cap sucessfully.
However, when I want to delete it, or install it again, it raise error:
```
Traceback (most recent call last):
  File "shadysim_isim.py", line 491, in <module>
    ac.delete_aid(args.delete_app)
  File "shadysim_isim.py", line 257, in delete_aid
    return self.send_wrapped_apdu_checksw(apdu)
  File "shadysim_isim.py", line 246, in send_wrapped_apdu_checksw
    raise RuntimeError("SW match failed! Expected %s and got %s." % (sw.lower(), response[1]))
RuntimeError: SW match failed! Expected 9000 and got 6a88.
```

My delete command is 
```
 python2 shadysim_isim.py  --pcsc  -d d07002CA449001 --kic KIC1 --kid KID1
```

Did you experience this issue?

**Comment by liuwei-network** [comment]
When I try to install it again, it raise error:
```
Traceback (most recent call last):
  File "shadysim_isim.py", line 494, in <module>
    ac.load_app(args.load_app)
  File "shadysim_isim.py", line 369, in load_app
    self.load_aid_raw(aid, data, len(data) / 2)
  File "shadysim_isim.py", line 271, in load_aid_raw
    self.send_wrapped_apdu_checksw('80e60200' + ('%02x' % (len(data) / 2)) + data + '00c0000000')
  File "shadysim_isim.py", line 246, in send_wrapped_apdu_checksw
    raise RuntimeError("SW match failed! Expected %s and got %s." % (sw.lower(), response[1]))
RuntimeError: SW match failed! Expected 9000 and got 6985.
```

**Comment by liuwei-network** [comment]
I'm using sysmoISIM-SJA2.

**Comment by mrlnc** [comment]
if you resolved the error, would you mind sharing your experience?

I've just added a little note on uninstalling (see here: https://github.com/mrlnc/HelloSTK2#uninstall), I think you need to use `--list-applets` first, search for the correct AID, then use `--delete` with that AID. could be the issue you saw, too?

**Comment by liuwei-network** [comment]
Sure.
Yes, I have the same solution as you. 
We use instance-aid to install applet, but we need AID to delete it.
Thanks for you uninstalling notes.

**Comment by mrlnc** [comment]
Actually I was running into the same problem every now and then. Really annoying. So I tried to make the `shadysim_isim` script a bit more helpful:
https://github.com/mrlnc/pysim/blob/install-applets/stk_applet_manager.py

- Python3 converted
- reads AIDs from the CAP file, to avoid mismatches
- checks if applet is already loaded
- more structured `--help`

```console
$ python3 ./stk_applet_manager.py --pcsc 8 --kic xxx --kid xxx --file ../hello-stk/build/ImsiChange.cap --load
Waiting for card…
Reading CAP file.
File contents ../hello-stk/build/ImsiChange.cap
| Package AID: d07002ca44
| Applet Count: 1
| Applet #0: AID d07002ca44900102
Warning! Applet with AID d07002ca44 already present on card. Loading will likely fail. Use a different AID, or delete the applet currently on card using `--delete d07002ca44`
```

🤷  just leaving this here, maybe it's helpful

**Comment by liuwei-network** [comment]
@mrlnc Thanks, it will help me a lot.

Currently, I am suffering from another problem and would like to ask you for advice.

I want to use `javacardx.framework.math.BigNumber` API(https://docs.oracle.com/javacard/3.0.5/api/index.html) and the javacard website shows that it has supported it since SDK 2.2.2.

So, I changed your `build.xml`, modified the targetsdk to jc222_kit and I can compile the cap without any problem.
I defined a BigNumber variable in `process()`.
But when I install it to sysmoISIM-SJA2, it reports an error RuntimeError: `SW match failed! Expected 9000 and got 6985 (Conditions of use not satisfied.)`
I would like to know if sysmoISIM-SJA2 doesn't support 2.2.2 SDK or if my installation command or sim-tools needs to be modified accordingly.
I tried to replace api21.jar in sim-tools, but I still get the error.

Here is my HelloSTK2.java and build.xml

[1.zip](https://github.com/mrlnc/HelloSTK2/files/12621789/1.zip)

I'm very sorry to bother you again.

**Comment by mrlnc** [comment]
Not sure either. The [sysmoUSIM-manual](https://www.sysmocom.de/manuals/sysmousim-manual.pdf) mentions SDK 2.2.*1*, but not sure if that's the case specifically for the SJA2 card.

**Comment by mrlnc** [comment]
In any case, feel free to document your progress in this issue, I think it's always great to have some "archive" for sysmo-USIM specific stuff - other's who have the same issue might find your notes later :)

**Comment by liuwei-network** [comment]
Sure, thank you anyway :)
I will write my progress here if I solve this issue.
